### ISSUE TITLE
On last version

### ISSUE THREAD

**Issue by chronoss09** [zoltx23/SimplyU#5]
<a href="https://gyazo.com/320874bcf66e9e46e322ef8781b82c25"><img src="https://i.gyazo.com/320874bcf66e9e46e322ef8781b82c25.png" alt="https://gyazo.com/320874bcf66e9e46e322ef8781b82c25" width="867"/></a>

**Comment by zoltx23** [comment]
This appears to be some sort of image rendering alignment issue. I'll try and fix this with a quick Canary build later today. I apologise for the issue!

**Comment by zoltx23** [comment]
I will be releasing a Canary Build sometime tomorrow, with a fix for this rendering issue. Thanks for waiting!
